import React from 'react'

const tableData = [
  {
    id: 0,
    title: "What Personal "
  }
]

const defination = [
  {
    id: 0,
    title: "Account",
    content: "a unique account created for You to access our Service or parts of our Service."
  },
  {
    id: 1,
    title: "Company",
    content: "referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Redwine Digital , CRYSTAL PLAZA, New Link Rd, Phase D, Shastri Nagar,Andheri West, Andheri, Maharashtra 400053. <br /> For the purpose of the GDPR, the Company is the Data Controller."

  },
  {
    id: 2,
    title: "Cookies",
    content: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses."
  },
  {
    id: 3,
    title: "Country",
    content: "refers to: Maharashtra, India"
  },
  {
    id: 4,
    title: "Data Controller",
    content: "for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data. Device means any device that can access the Service such as a computer, a cellphone or a digital tablet."
  },
  {
    id: 5,
    title: "Personal Data ",
    content: "is any information that relates to an identified or identifiable individual. <br /> For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity."

  },
  {
    id: 6,
    title: "Services",
    content: "refers to the Website."
  },
  {
    id: 7,
    title: "Service Provider",
    content: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors. Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."
  },
  {
    id: 8,
    title: "Website",
    content: "refers to Barcode Entertainment (Barcode Experiential Marketing ), accessible from www.barcodeent.com"
  },
  {
    id: 9,
    title: "You",
    content: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. <br /> Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service."
  },
]



const Privacy = () => {
  return (
    <div className="redwine__privacy">
      <div className="redwine__privacy-title">
        <h1>Privacy Policy</h1>
        <p>Last Edited Oct 2,2022</p>
      </div>
      <div className="redwine__privacy-content">
        <div className="left">
          <div className="left__title">
            <h1>This Privacy Policy will help you better understand how we collect, use, and share your personal information.</h1>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects you.
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          </div>
          <br />
          <br />
          <div className="left__content">
            <h1>INTERPRETATION AND DEFINITIONS</h1>
            <br />
            <h2>Interpretation</h2>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <br />
            <h2>Definations</h2>
            <p style={{ marginBottom: "1rem" }}>For the purposes of this Privacy Policy:</p>

            {defination.map(item => (
              <p key={item.id} style={{ marginBottom: "1rem" }}>
                <strong>{item.title}</strong> {" "}
                {item.content}
              </p>
            ))}
            <br />
            <br />

            <h1>COLLECTING AND USING YOUR PERSONAL DATA</h1>
            <br />
            <h2>Types of Data Collected</h2>
            <br />
            <br />
            <br />
            <p> <strong>Personal Data</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <br />
            <p> <strong>Usage Data</strong> Usage Data Usage Data is collected automatically when using the Service. <br />Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <br />
            <p> <strong>Tracking Technologies and Cookies</strong> We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <div className="list" style={{ padding: "1rem 2rem" }}>
              <ul type="disc">
                <li>
                  <p><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                </li>
                <li>
                  <p><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</p>
                </li>
                <li>
                  <p><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies here:</p>
                </li>
              </ul>
            </div>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            <p><strong>Necessary / Essential Cookies</strong></p>
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            <p><strong>Functionality Cookies</strong></p>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website. <br />For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
            <br />
            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <br />
            <br />
            <p><strong>To provide and maintain our Service,</strong>including to monitor the usage of our Service.</p>
            <br />
            <p><strong>To manage Your Account:</strong>to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
            <br />
            <p><strong>For the performance of a contract:</strong>the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
            <br />
            <p><strong>To contact You</strong>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
            <br />
            <p><strong>To Provide You</strong>with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
            <br />
            <p><strong>To manage Your requests:</strong> attend and manage Your requests to Us.</p>
            <br />
            <p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
            <br />
            <p><strong>For other purposes:</strong>We  may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
            <br />
            <br />
            <p>We may share Your personal information in the following situations:</p>

            <div className="list" style={{ padding: "1rem 2rem" }}>
              <ul type="disc">
                <li>
                  <p><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</p>
                </li>
                <li>
                  <p><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</p>
                </li>
                <li>
                  <p><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
                </li>
                <li>
                  <p><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</p>
                </li>
                <li>
                  <p><strong>With other users: </strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</p>
                </li>
                <li>
                  <p><strong>With Your consent: </strong> We may disclose Your personal information for any other purpose with Your consent.</p>
                </li>
              </ul>
            </div>
          </div>
          <br />
          <h2>Retention of Your Personal Data</h2>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
          <br />
          <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
          <br />
          <br />
          <h2>Transfer of Your Personal Data</h2>
          <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
          </p>
          <br />
          <h2>Disclosure of Your Personal Data</h2>
          <br />
          <p><strong>Business Transactions</strong></p>
          <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          <p><strong>Law enforcement</strong></p>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          <p><strong>Other legal requirements</strong></p>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

          <div className="list" style={{ padding: "1rem 2rem" }}>
            <ul type="disc">
              <li>
                <p>Comply with a legal obligation</p>
              </li>
              <li>
                <p>Protect and defend the rights or property of the Company</p>
              </li>
              <li>
                <p>Prevent or investigate possible wrongdoing in connection with the Service</p>
              </li>
              <li>
                <p>Protect the personal safety of Users of the Service or the public</p>
              </li>
              <li>
                <p>Protect against legal liability</p>
              </li>
            </ul>
          </div>
          <h2>Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <br />
          <br />
          <br />
          <h1>GDPR PRIVACY</h1>
          <br />
          <br />
          <br />
          <p>Legal Basis for Processing Personal Data under GDPR
            <br /> We may process Personal Data under the following conditions:</p>
          <div className="list" style={{ padding: "1rem 2rem" }}>
            <ul>
              <li><p>Consent: You have given Your consent for processing Personal Data for one or more specific purposes.</p></li>
            </ul>
          </div>
          <p>Performance of a contract: Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</p>
          <div className="list" style={{ padding: "1rem 2rem" }}>
            <ul>
              <li><p>Legal obligations: Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</p></li>
              <li><p>Vital interests: Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</p></li>
              <li><p>Public interests: Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</p></li>
              <li><p>Legitimate interests: Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</p></li>
            </ul>
          </div>

          <br />
          <br />
          <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>
          <br />
          <h2>Your Rights under the GDPR</h2>
          <p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.</p>
          <br />
          <p>You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>

          <div className="list" style={{ padding: "1rem 2rem" }}>
            <ul>
              <li><p>Request access to Your Personal Data. The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.</p></li>
              <li><p>Request correction of the Personal Data that We hold about You. You have the right to have any incomplete or inaccurate information We hold about You corrected.</p></li>
              <li><p>Object to processing of Your Personal Data. This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</p></li>
              <li><p>Request erasure of Your Personal Data. You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</p></li>
              <li><p>Request the transfer of Your Personal Data. We will provide to You, or to a third- party You have chosen, Your Personal Data in a structured, commonly used, machine- readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</p></li>
              <li><p>Withdraw Your consent. You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</p></li>
            </ul>
          </div>
          <h2>Exercising of Your GDPR Data Protection Rights</h2>
          <p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible. You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>
          <br />
          <h2>Children&apos;s Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. <br />If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.</p>
          <br />
          <h2>Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit. <br />We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          <br />
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy
            <br />
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
          <br />
          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:- By email: info@redwine.digital</p>
        </div>
      </div>
    </div>
  )
}

export default Privacy